### ISSUE TITLE
[22w12a] macOS video scaling

### ISSUE THREAD

**Issue by kwpugh** [shedaniel/BetterLoadingScreen#11]
<img width="1312" alt="Screen Shot 2022-03-28 at 8 33 32 AM" src="https://user-images.githubusercontent.com/8809210/160409663-a57c9c49-f0d2-43ee-9987-615752d98bc5.png">

Minecraft 22w12a
Latest MultiMC launcher

After launch, I cannot  change the scaling without the above effect occurring.

**Comment by shedaniel** [comment]
1.19 not supported

**Comment by kwpugh** [comment]
ok, I saw this and gave it a try.
![Screen Shot 2022-03-28 at 9 33 32 AM](https://user-images.githubusercontent.com/8809210/160421785-03b08fa3-9db2-4a9d-996f-65e7459563f0.png)
