### ISSUE TITLE
Possible Mod Incompatibility or Mod Confliction with Modern UI (1.18.1)

### ISSUE THREAD

**Issue by Coraline77447** [shedaniel/BetterLoadingScreen#16]
Minecraft: 1.18.1
Forge: 1.18.1, 39.1.2
Better Loading Screen: 1.1.1 to 1.3.1
Modern UI: 3.4.0.99

Better Loading Screen possibly might not be compatible or is conflicting with Modern UI (1.18.1) and they're not working together whenever Better Loading Screen or Modern UI isn't installed. 
(but like I've said in my comment in the mod's comment section that I would never uninstall Modern UI unless proven necessary to do so, only if Modern UI isn't working like if it keeps crashing the game like how it's 1.18.2 versions kept crashing the game)
I think that this problem between these two mods is an incompatibility issue or possibly a mod confliction issue since Modern UI does some rendering but not like OptiFine does.

Here are two crash reports along with two log files that were created on the 26th of March, which they're similar to each other. They both say that the issue is being caused by Modern UI but how can you explain to me that when I uninstalled Better Loading Screen the game loads in with Modern UI (along with all of my other mods that I play with) just fine then? 

Crash Report 1: https://pastebin.com/PZGf9hgJ
Crash Report 2: https://pastebin.com/NUGJbXq3

Log 1: [2022-03-26-1.log.gz](https://github.com/shedaniel/BetterLoadingScreen/files/8391087/2022-03-26-1.log.gz)
Log 2: [2022-03-26-2.log.gz](https://github.com/shedaniel/BetterLoadingScreen/files/8391090/2022-03-26-2.log.gz)

This might happen in 1.18.2 as well that both this mod and Modern UI (if itself doesn't keep crashing the game that is..) may have the same problem(s) when they're installed together.

**Comment by BloCamLimb** [comment]
Update Modern UI to 3.4.3, it works in 1.18.1 as well.

**Comment by shedaniel** [comment]
Thanks for resolving this issue!
