### ISSUE TITLE
Incompatibility with Quilt

### ISSUE THREAD

**Issue by Cccc-owo** [shedaniel/BetterLoadingScreen#20]
Just like the title.
```Minecraft 1.18.2 with Quilt Loader 0.16.0-beta.8```
[latest.log](https://github.com/shedaniel/BetterLoadingScreen/files/8541235/latest.log)
Mods:
```
better-loading-screen-1.4.0.jar
lazydfu-0.1.2.jar
modmenu-3.1.1.jar
qsl-1.1.0-beta.4_qfapi-1.0.0-beta.8_fapi-0.51.1_mc-1.18.2.jar
```

**Comment by shedaniel** [comment]
Please do not report issues if you are having a non-official fabric fork, this includes Aristoris and Quilt.
Quilt support is planned but not expected soon as I am busy with other things.
